name = "EuclidianNormalizingFlows"
uuid = "eb90128f-7c94-4cd6-9130-4bb7c9abac9d"
version = "0.1.0"


[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
ForwardDiffPullbacks = "450a3b6d-2448-4ee1-8e34-e4eb8713b605"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
ArgCheck = "1, 2.0"
ArraysOfArrays = "0.4, 0.5"
ChainRulesCore = "0.9.44, 0.10"
Distributions = "0.21.10, 0.22, 0.23, 0.24, 0.25"
ElasticArrays = "1.2.3"
ForwardDiffPullbacks = "0.1.1"
Optim = "0.19,0.20, 0.21, 0.22, 1"
SpecialFunctions = "0.10, 1"
StatsBase = "0.32, 0.33"
ValueShapes = "0.9"
ZygoteRules = "0.2"
julia = "1.3"
